### ISSUE TITLE
Not working on current Q2A script

### ISSUE THREAD

**Issue by andymike123** [svivian/q2a-edit-history#19]
Cause current q2a script crash and not display. Probably, this plugin is too old compare to current q2a script
Thanks

**Comment by svivian** [comment]
Can you explain the problem in more detail? What error are you getting?

The plugin works fine for me on the current Q2A version.

**Comment by andymike123** [comment]
Actually, i am using a customize theme with current q2a (just css), but not touch any core q2a. When i used your script, my frontend and backend blank out, it is saying http error 500. 
Thank you

**Comment by svivian** [comment]
Do you have any errors in your error logs? And what version of PHP are you using?

**Comment by andymike123** [comment]
[14-Jul-2016 22:00:14 Europe/Berlin] PHP Fatal error:  require_once(): Failed opening required 'testwebsite/site-include/qa-app-users.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in testwebsite/site-plugin/edit-history-master/qa-edit-history.php on line 7

my php is 5.6

Thank you for your help

**Comment by svivian** [comment]
It seems like the `QA_INCLUDE_DIR` constant is being set incorrectly somehow. Do you have the file `qa-include/qa-app-users.php` on your site? Your error there suggests the folders have been renamed to `site-include` instead of `qa-include`.

Possibly you need to either put your folders back to the Q2A names, or fix `QA_INCLUDE_DIR` to point to the proper path.

**Comment by andymike123** [comment]
Thanks, it is now working. How can i see user or anyone edit history? I already set for admin to rollback or delete revision.

**Comment by svivian** [comment]
There is no way to do that in the plugin currently. You can only view the history of each post.
